spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: hasan
    password: hasan123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        store_data_at_delete: true
        default_schema: request_ms
swagger-ui:
  path: /swagger-ui.html
  enabled: true

server:
  port: 8082

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: hasan
#    password: hasan123
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        store_data_at_delete: true
#        default_schema: request_ms
#swagger-ui:
#  path: /swagger-ui.html
#  enabled: true
#
#server:
#  port: 8082
